version: "3"
services:
    elasticsearch:
        image: "docker.elastic.co/elasticsearch/elasticsearch:7.7.0"
        environment:
            - "discovery.type=single-node"
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - elk

    kibana:
        image: "docker.elastic.co/kibana/kibana:7.7.0"
        ports:
            - "5601:5601"
        links:
            - elasticsearch
        networks:
            - elk
        depends_on:
            - elasticsearch

    filebeat:
        image: "docker.elastic.co/beats/filebeat:7.7.0"
        user: root
        links:
            - elasticsearch
            - kibana
        networks:
            - elk            
        volumes:
            - "$(pwd)/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro"
            - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            - ELASTICSEARCH_HOSTS: 
 
networks:
  elk:
    driver: bridge